[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "E", "W",       # pycodestyle
    "F",            # pyflakes
    "I",            # isort
    "PLC", "PLE",   # pylint
    "UP",           # pyupgrade
]
ignore = [
    "E402",
    "E501",  # let ruff-format handle line-length
    "E741",
]

[tool.ruff.lint.isort]
known-first-party = ["ciadmin", "build_decision", "fxci_config_taskgraph"]
known-third-party = ["taskcluster", "tcadmin", "taskgraph"]
