# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at http://mozilla.org/MPL/2.0/.

import pytest
from tcadmin.resources import Resources
from tcadmin.util.matchlist import MatchList

from ciadmin import boot
from ciadmin.generate import in_tree_actions, scm_group_roles


class TestKeepCurrentResource:
    """
    `_keep_current_resource` decides whether a live Taskcluster resource is a
    real deletion candidate for a `--resources` subset diff.
    """

    owned_ids = {"Role=hook-id:project-releng/cron-task-foo"}
    owned_patterns = MatchList(["Role=hook-id:project-gecko/in-tree-action-.*"])

    def test_kept_when_generated_even_if_owned_elsewhere(self):
        # We generated it, so it must be compared (e.g. to detect scope changes)
        # even though an unselected generator also owns it.
        generated = {"Role=hook-id:project-releng/cron-task-foo"}
        assert boot._keep_current_resource(
            "Role=hook-id:project-releng/cron-task-foo",
            generated,
            self.owned_ids,
            self.owned_patterns,
        )

    def test_dropped_when_owned_by_unselected_id(self):
        # Generated by an unselected generator (real id), not by us: not a
        # deletion, just skipped.
        assert not boot._keep_current_resource(
            "Role=hook-id:project-releng/cron-task-foo",
            set(),
            self.owned_ids,
            self.owned_patterns,
        )

    def test_dropped_when_owned_by_unselected_pattern(self):
        # Owned by a network-requiring unselected generator (pattern fallback).
        assert not boot._keep_current_resource(
            "Role=hook-id:project-gecko/in-tree-action-1-generic/*",
            set(),
            self.owned_ids,
            self.owned_patterns,
        )

    def test_kept_when_not_owned_by_unselected(self):
        # Only the selected generator owns it: a genuine deletion must survive.
        assert boot._keep_current_resource(
            "Role=repo:github.com/mozilla/x:branch:main",
            set(),
            self.owned_ids,
            self.owned_patterns,
        )


class TestPatternKinds:
    def test_plain_pattern(self):
        assert boot._pattern_kinds(["Role=mozilla-group:.*"]) == {"Role"}

    def test_negative_lookahead_prefix(self):
        # manage_with_exclusions produces `(?!Kind=excl)Kind=...`; the kind must
        # be read past the leading lookahead, not from inside it.
        assert boot._pattern_kinds(["(?!Hook=project-fuzzing/.*)Hook=.*"]) == {"Hook"}

    def test_client_lookahead_after_equals(self):
        assert boot._pattern_kinds(
            ["Client=(?!mozilla-auth0/|static/taskcluster/)"]
        ) == {"Client"}

    def test_multiple(self):
        assert boot._pattern_kinds(
            ["Role=repo:.*", "(?!WorkerPool=proj-fuzzing/.*)WorkerPool=.*"]
        ) == {"Role", "WorkerPool"}


@pytest.mark.asyncio
async def test_collect_unselected_ownership(mock_ciconfig_file, set_environment):
    """
    Unselected generators whose kind is diffed contribute their real generated
    ids, except network-requiring ones (in_tree_actions), which contribute
    narrow patterns.
    """
    mock_ciconfig_file(
        "actions.yml",
        [{"trust_domain": "gecko", "levels": [1], "action_perms": ["generic"]}],
    )
    mock_ciconfig_file(
        "projects.yml",
        {
            "proj1": dict(
                repo="https://hg.mozilla.org/foo/proj1",
                repo_type="hg",
                access="scm_level_3",
                branches=[{"name": "default"}],
                trust_domain="gecko",
            )
        },
    )

    with set_environment("test-env"):
        owned_ids, owned_patterns = await boot._collect_unselected_ownership(
            [in_tree_actions, scm_group_roles], relevant_kinds={"Role"}
        )

    # scm_group_roles is generated -> its real ids are known.
    assert "Role=mozilla-group:active_scm_level_1" in owned_ids
    assert "Role=mozilla-group:active_scm_level_3" in owned_ids

    # in_tree_actions requires network -> narrow pattern fallback, no generation.
    assert owned_patterns.matches(
        "Role=hook-id:project-gecko/in-tree-action-1-generic/*"
    )
    assert not owned_patterns.matches("Role=repo:github.com/mozilla/x:branch:main")


@pytest.mark.asyncio
async def test_collect_unselected_ownership_skips_irrelevant_kinds():
    """
    A generator whose kinds don't overlap what is being diffed is never
    generated -- so an unrelated subset diff (e.g. worker_pools) is not coupled
    to it. scm_group_roles only owns Roles; diffing WorkerPools must skip it
    without touching any config.
    """
    owned_ids, owned_patterns = await boot._collect_unselected_ownership(
        [scm_group_roles], relevant_kinds={"WorkerPool"}
    )
    assert owned_ids == set()
    assert list(owned_patterns) == []


@pytest.mark.asyncio
async def test_in_tree_actions_register_managed_is_network_free(mock_ciconfig_file):
    """
    `register_managed` must declare patterns using only local config so that,
    in subset mode, an unselected in_tree_actions does not trigger the expensive
    `.taskcluster.yml` hashing that `update_resources` performs.
    """
    mock_ciconfig_file(
        "actions.yml",
        [{"trust_domain": "gecko", "levels": [1, 3], "action_perms": ["generic"]}],
    )

    resources = Resources()
    # No taskcluster/GitHub session is set up here; if register_managed reached
    # for the network this call would fail.
    await in_tree_actions.register_managed(resources)

    patterns = list(resources.managed)
    assert "Hook=project-gecko/in-tree-action-.*" in patterns
    assert "Role=hook-id:project-gecko/in-tree-action-.*" in patterns
