# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at http://mozilla.org/MPL/2.0/.

import pytest

from ciadmin.boot import RESOURCE_MODULES


@pytest.mark.asyncio
async def check_modules_manage_disjoint_resources(generate_resources):
    """
    Ensures that no module's declared `managed` MatchList (see `ciadmin.boot`)
    also matches a resource actually generated by a *different* module.

    Every module's own generated resources are already guaranteed to match
    its own `managed` list (`boot._managed_resources` enforces this via a
    scoped `Resources` object), so a resource should be matched by *exactly
    one* module's `managed` list -- its own. If more than one module's list
    matches it, that's either an outright id collision or a module's
    `managed` pattern being too broad -- e.g. accidentally claiming a
    `hook-id:*` namespace that's actually generated (and legitimately owned)
    elsewhere. The latter would otherwise go unnoticed here but make
    `tc-admin diff --only <module>` (which scopes `resources.managed` to
    just that module's patterns) report other modules' resources as
    spurious deletions.
    """
    conflicts = []

    for name in RESOURCE_MODULES:
        for resource in await generate_resources(name):
            claimants = [
                other_name
                for other_name, other_module in RESOURCE_MODULES.items()
                if other_module.managed.matches(resource.id)
            ]
            if len(claimants) > 1:
                conflicts.append((resource.id, claimants))

    if conflicts:
        print(
            "The following resources are claimed by more than one module's "
            "`managed` list:\n"
            + "\n".join(f"{rid}: {claimants}" for rid, claimants in conflicts)
        )
    assert not conflicts
