[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
python_classes = Check*
python_files = check_*.py
python_functions = check_*

cache_dir = $HOME/.mozbuild/ci-admin/pytest-cache
