# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at http://mozilla.org/MPL/2.0/.

import os
import re
import sys

import click
from tcadmin.appconfig import AppConfig
from tcadmin.main import main
from tcadmin.resources import Resources

from ciadmin import modify
from ciadmin.generate import (
    clients,
    cron_tasks,
    git_pushes,
    grants,
    hg_pushes,
    hooks,
    in_tree_actions,
    scm_group_roles,
    worker_pools,
)
from ciadmin.generate.ciconfig.externally_managed import manage_patterns

RESOURCES = {
    "clients": clients,
    "cron_tasks": cron_tasks,
    "git_pushes": git_pushes,
    "grants": grants,
    "hg_pushes": hg_pushes,
    "hooks": hooks,
    "in_tree_actions": in_tree_actions,
    "scm_group_roles": scm_group_roles,
    "worker_pools": worker_pools,
}


async def filter_resources_by_modules(resources, modules):
    """Filter `resources` to the ones generated by the given modules.

    Reuses each module's MANAGED_PATTERNS and exclusion handling.
    """
    scope = Resources()
    for module in modules:
        await manage_patterns(scope, module.MANAGED_PATTERNS)
    filtered = [r for r in resources.resources if scope.is_managed(r.id)]
    return Resources(resources=filtered, managed=scope.managed)


appconfig = AppConfig()

appconfig.options.add(
    "--environment",
    required=True,
    help="environment for which resources are to be generated",
)

appconfig.check_path = os.path.join(os.path.dirname(__file__), "check")

# Registered first so the client is closed even when `modify_resources`
# rejects the environment.
appconfig.modifiers.register(modify.close_github_client)
appconfig.modifiers.register(modify.modify_resources)

appconfig.description_prefix = (
    "*DO NOT EDIT* - This resource is configured automatically by "
    + "[ci-admin](https://github.com/mozilla-releng/fxci-config).\n\n"
)


def boot():
    if not os.environ.get("GITHUB_TOKEN") and not (
        os.environ.get("GITHUB_APP_ID") and os.environ.get("GITHUB_APP_PRIVKEY")
    ):
        click.echo(
            "WARNING: GITHUB_TOKEN is not present in the environment; you may run into rate limits querying for GitHub branches",
            err=True,
        )

    def has_arg(name):
        "True if a `--name value` or `--name=value` argument is present in sys.argv."
        if any(arg.startswith(f"{name}=") for arg in sys.argv):
            return True
        return name in sys.argv

    @click.command(
        context_settings={"ignore_unknown_options": True, "allow_extra_args": True}
    )
    @click.option(
        "--resources",
        required=False,
        default="all",
        help=f"Comma-separated list of resources to generate. Allowed values are: all,{','.join(RESOURCES.keys())}",
    )
    def register_resources_and_run(resources: str):
        resources_list = resources.split(",")
        is_all = "all" in resources_list

        if is_all:
            for module in RESOURCES.values():
                appconfig.generators.register(module.update_resources)
        else:
            for reso in resources_list:
                if module := RESOURCES.get(reso, None):
                    click.echo(f"Registering resource: {reso}", err=True)
                    appconfig.generators.register(module.update_resources)
                else:
                    click.echo(f"Ignoring invalid resource: {reso}.", err=True)
            if "clients" not in resources_list:
                from tcadmin.current import clients  # noqa: PLC0415

                async def fetch_clients(resources):
                    return

                clients.fetch_clients = fetch_clients

            if has_arg("--generated"):
                # `--generated` loads a complete resource set from disk
                # rather than running generators live, so registering only
                # some generators above has no effect (none of them run).
                # Narrow the loaded set down to the requested resource
                # types afterwards instead.
                import tcadmin.generate  # noqa: PLC0415

                modules = [
                    RESOURCES[reso] for reso in resources_list if reso in RESOURCES
                ]
                load_resources = tcadmin.generate.resources

                async def scoped_resources(*args, **kwargs):
                    loaded = await load_resources(*args, **kwargs)
                    return await filter_resources_by_modules(loaded, modules)

                tcadmin.generate.resources = scoped_resources

        # Remove the --resources arguments from sys.argv so inner "click.command"s don't complain
        # Handle parameter with =
        arg_regex = re.compile(r"^--resources\=.*")
        sys.argv = [arg for arg in sys.argv if not arg_regex.match(arg)]
        # Handle parameter with space
        while "--resources" in sys.argv:
            reso_arg_index = sys.argv.index("--resources")
            sys.argv = sys.argv[:reso_arg_index] + sys.argv[reso_arg_index + 2 :]

        main(appconfig)

    # if --help, then add the option to global and let main() handle it
    if "--help" in sys.argv:
        appconfig.options.add(
            "--resources",
            required=False,
            default="all",
            help=f"Comma-separated list of resources to generate. Allowed values are: all,{','.join(RESOURCES.keys())}",
        )
        main(appconfig)
    else:
        register_resources_and_run()
